version: '3.8'

services:
  postgres-db:
    image: postgres:15

    container_name: visao_futuro

    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123123123'
      POSTGRES_DB: 'visao_futuro'

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres-data:
    driver: local